### ISSUE TITLE
PHP 7 error

### ISSUE THREAD

**Issue by mark-app** [matthiask/swisdk2#1]
Non-static method smtp::connect() should not be called statically in htmlMimeMail5.php on line 768

**Comment by matthiask** [comment]
I'm afraid the code in question hasn't been updated since 2007 (!!). 

I have switched from PHP to Python/Django in 2008/2009 and haven't looked back. I'm sorry to say I cannot really help you. My PHP knowledge isn't even rusty anymore, it decayed completely.
